# Generated by Django 5.1 on 2025-11-24 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTOProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ttoprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('office_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('therapeutic_focus_tags', models.CharField(blank=True, help_text="Comma-separated tags, e.g., 'Oncology, Neurology'", max_length=500)),
                ('trl_range_interest', models.CharField(blank=True, help_text="e.g., 'TRL 1-3, TRL 4-6'", max_length=100)),
            ],
        ),
    ]
